codecov:
  require_ci_to_pass: false

coverage:
  precision: 2
  round: down
  range: "70...100"
  status:
    project:
      default:
        # basic
        target: 10%
        threshold: 0%
        if_ci_failed: error
