codecov:
  require_ci_to_pass: true

coverage:
  precision: 2
  round: down
  range: "70...100"
  status:
    default_rules:
      # basic
      target: 80
      threshold: 0%
      base: auto
      paths:
        - "src"
